### ISSUE TITLE
Can The Server Handel all requests on a single threads ?

### ISSUE THREAD

**Issue by omarsaad26** [AbdallahSalah003/MediConnect#1]
I Want to make the server handel all requests on a single threads can you please tell me if it's possible to make this happen ?

**Comment by AbdallahSalah003** [comment]
Yes, it's possible to design a server that handles all requests on a single thread. This approach is commonly referred to as the "single-threaded" or "event-driven" model. In Java, you can achieve this using non-blocking IO (NIO) or asynchronous IO (AIO) with Java's NIO package.
